# Site
repository: Alokkiitdh.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alok
title: AI Engineer
email: aloklashok@gmail.com
# website: www.github.com/Alokiitdh/Alokkiitdh.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Alokiitdh
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: __spartan___x
linkedin_username: alok-b58317148
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Hugging Face
  icon: fa fa-connectdevelop
  url: https://huggingface.co/AlokVishwakarma

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name’s Alok and I’m an AI Engineer. I have completed my M.Tech. in Communication Signal Processing and Machine Learning from IIT Dharwad, where I focused on machine learning and deep learning.

  I have experience building intelligent multi-agent systems using LangGraph, LangChain, and LLMs. I’ve developed production-ready APIs with FastAPI, integrated external tools like web search, and worked with vector databases like FAISS and Pinecone for efficient semantic retrieval. I’ve also worked on advanced RAG pipelines, implemented real-time object tracking and counting systems, and built generative and classification models using CNNs, Vision Transformers, and diffusion techniques.

  Along the way, I’ve gained strong problem-solving, debugging, and collaboration skills, and I’m passionate about building real-world AI applications.


content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tipstat 
        link: tipstat.com
        sub_title: AI Engineer Intern
        caption: May 2025 - Present
        quote: >
          Building intelligent systems with LangGraph, FastAPI, and LLMs to solve real-world AI challenges.
        description: | # this will include new lines to allow paragraphs
            I have designed and evaluated Retrieval-Augmented Generation (RAG) pipelines using LangGraph, LangChain, and LLMs, with performance benchmarking through RAGAS. My work includes building agentic workflows using LangGraph and leveraging LangSmith for tracing, debugging, and automating complex, multi-step behaviors.

            I’ve developed production-ready APIs using FastAPI, integrated external tools like web search into multi-agent systems, and used the command-line interface (CLI) to run, test, and operate these systems efficiently.

            Working in a team of four, I contributed to two major projects:

            - **Municipal Solid Waste Research Agentic Framework** – Built using LangGraph, this system accurately searches and classifies waste composition, including food waste (veg/non-veg) and plastic waste subdivided into seven major categories, delivering high-precision results.

            - **Contractor AI** – Developed an AI-powered call analysis system that performs sentiment analysis, lead quality classification (HOT, MEDIUM, COLD), conversion probability estimation, and overall scoring. Implemented behavioral key phrase extraction and a smart sales rep assignment module to optimize lead follow-up.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Indian Institute of Technology, Dharwad
        caption: 2023 - 2025
        sub_title: M.Tech – Communication Signal Processing and Machine Learning (CSPML)
        cpi: 8.07/10
        quote: >
          Where my passion for AI and machine learning turned into hands-on expertise.
        description: | # this will include new lines to allow paragraphs
          During my time at IIT Dharwad, I developed a strong foundation in machine learning, deep learning, and signal processing. The program provided both theoretical depth and practical exposure, allowing me to work on real-world projects involving generative AI, vision transformers, and diffusion models.

          I also gained experience in research-driven development, time-bound problem solving, and collaborative teamwork—all of which shaped my journey as an AI engineer.
      - layout: left
        title: Govt. College of Engineering and Technology, Bikaner
        caption: 2016 - 2020
        sub_title: B.Tech – Electronics and Communication Engineering
        cpi: 9.0/10
        quote: >
          The place where I built my technical foundation and curiosity for AI.
        description: | # this will include new lines to allow paragraphs
            I completed my undergraduate studies in Electronics and Communication Engineering, where I developed strong fundamentals in mathematics, signal processing, and embedded systems. This is where I was first introduced to programming, machine learning, and computer vision, which later evolved into my core areas of interest. I actively participated in technical events and projects, laying the groundwork for my future in AI.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: AI-interviewer
        caption: July 2025
        # icon: fab fa-github
        link: github.com/Alokiitdh/ai_interviewer
        # link_text: Project Website
        # additional_links:
          # - title: AI-interviewer
          #   icon: fab fa-github
          #   url: github.com/Alokiitdh/ai_interviewer
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A smart interview tool that asks questions, checks your answers, and gives feedback and a final score – all through a simple chat in your terminal.
        description: | # this will include new lines to allow paragraphs
          I built an AI-powered technical interviewer using a command-line interface (CLI). The system simulates a real interview by dynamically generating open-ended technical questions on a chosen topic (like Machine Learning, Networks, etc.), accepting user responses, and evaluating them with structured scoring and feedback. The project is built using LangGraph and OpenAI's GPT-4.1, and follows a multi-agent design with three core agents: the question_agent crafts theoretical questions, the evaluation_agent scores user answers based on clarity, depth, and accuracy, and the performance_agent compiles the final score and a concise performance summary. The architecture supports checkpointing, in-memory state tracking, and modular extensibility for future deployment via FastAPI or web interfaces. This project helped me explore advanced LLM workflows, prompt engineering, and the design of agent-based interview systems. It serves as a practical tool for technical interview practice and showcases how LLMs can be orchestrated in real-world applications.
     
      - layout: left
        title: AskMyPDF– RAG-based AI Chatbot
        caption: June 2025
        # icon: fab fa-github
        link: github.com/Alokiitdh/ask_my_pdf
        # link_text: Project Website
        # additional_links:
          # - title: AI-interviewer
          #   icon: fab fa-github
          #   url: github.com/Alokiitdh/ai_interviewer
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A private PDF chatbot that lets you upload any document and ask questions about it in real-time – fast, accurate, and memory-aware.

        description: | # this will include new lines to allow paragraphs
          I built an intelligent PDF chatbot using a Retrieval-Augmented Generation (RAG) architecture with a FastAPI backend. The system enables real-time, multi-turn conversations with uploaded PDFs via two endpoints—one for document upload and another for chatting with the document.It uses a LangGraph-powered agentic workflow to manage stateful interactions and maintain session-specific memory, allowing context-aware responses across turns. For retrieval, I integrated FAISS for efficient vector similarity search and used HuggingFace Transformers to generate document embeddings.The language model behind the system is Groq’s LLaMA 3.3-70B, which provides fast and contextually relevant answers. To ensure privacy, uploaded files are automatically cleaned up after use. I also evaluated the system using RAGAS to measure retrieval precision, answer faithfulness, and overall performance.This project gave me hands-on experience with building secure, production-ready RAG pipelines, advanced LangGraph workflows, and integrating high-speed inference APIs. It's a practical solution for document-based Q&A tasks, combining modern LLM capabilities with robust backend engineering.

      - layout: left
        title: CrowdFlow-Real-Time People Counting and Tracking
        caption: Jan. 2025- Feb. 2025
        # icon: fab fa-github
        link: github.com/Alokiitdh/CrowdFlow
        # link_text: Project Website
        # additional_links:
          # - title: AI-interviewer
          #   icon: fab fa-github
          #   url: github.com/Alokiitdh/ai_interviewer
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A real-time people detection and tracking system for crowd analytics, powered by YOLOv8 and the SORT tracking algorithm..

        description: | # this will include new lines to allow paragraphs
          I built a high-performance video analytics pipeline capable of detecting, tracking, and counting people in live camera feeds or pre-recorded videos. The system uses YOLOv8 for accurate person detection and integrates the SORT (Simple Online and Realtime Tracking) algorithm to assign persistent, unique IDs to each individual, enabling seamless tracking across frames.

          To support crowd analytics, I implemented custom directional counting logic that differentiates between upward and downward movement, ideal for entry–exit monitoring. The system supports region masking, allowing detection to be restricted to specific zones of interest—helpful for focusing on entrances, walkways, or event areas.

          For better situational awareness, I designed clear visual overlays including bounding boxes, tracker IDs, and real-time entry–exit counters. These features make the system well-suited for surveillance, public space monitoring, and event management.

          This project strengthened my expertise in real-time computer vision, multi-object tracking, and custom analytics logic, as well as integrating deep learning models into production-ready pipelines for video processing.


      - layout: left
        title: Diffusion Model- Realistic Face Generation with DDPM
        caption: May. 2024- Aug. 2024
        # icon: fab fa-github
        link: github.com/Alokiitdh/Diffusion-Model
        # link_text: Project Website
        # additional_links:
          # - title: AI-interviewer
          #   icon: fab fa-github
          #   url: github.com/Alokiitdh/ai_interviewer
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A diffusion-based generative model that creates high-quality, realistic anime faces from pure noise – vibrant, detailed, and artistically consistent.

        description: |
          I built a generative model using the Denoising Diffusion Probabilistic Model (DDPM) architecture to synthesize realistic anime face images. The system was trained on a custom-curated anime face dataset, enabling it to learn unique stylistic patterns and fine-grained facial details common in anime art.

          The core denoising process is powered by a state-of-the-art U-Net architecture, which progressively removes Gaussian noise over multiple timesteps to reconstruct clean, high-quality images. During training, the model learns the reverse diffusion process—mapping noisy inputs back to the underlying image distribution—allowing it to generate completely new faces from random noise during inference.

          Built with PyTorch, the model produces vibrant, stylistically consistent outputs that rival hand-drawn anime art. This project deepened my expertise in generative modeling, probabilistic diffusion processes, and advanced neural architectures, while providing hands-on experience in training large-scale image synthesis models.


      - layout: left
        title: DualWaveNet- Multimodal Vision Transformer for Depression Classification
        caption: Jan. 2024- March. 2024
        # icon: fab fa-github
        link: github.com/Alokiitdh/DualWaveNet
        # link_text: Project Website
        # additional_links:
          # - title: AI-interviewer
          #   icon: fab fa-github
          #   url: github.com/Alokiitdh/ai_interviewer
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A multimodal deep learning model that detects depression from speech using spectrogram and tempogram features – accurate, efficient, and transformer-powered.

        description: |
          I developed DualWaveNet, a deep learning system designed to classify individuals as Depressed or Non-Depressed using the EATD-Corpus dataset. The raw audio is converted into two complementary modalities: log-Mel spectrograms to capture frequency–time patterns, and tempograms to extract tempo and rhythm features.

          The model uses a dual-branch Vision Transformer (ViT-B/12) architecture, with each branch processing one modality independently. Through early fusion, the extracted features are combined to leverage both spectral and temporal cues for improved classification accuracy. To enhance inference efficiency, I integrated Token Merging (ToMe), which reduces computational cost while maintaining high accuracy.

          This multimodal architecture achieved significant improvements over baseline models—surpassing CNN-based models (66%) and vanilla ViT architectures (83%). The result is a robust, transformer-powered depression detection model that captures subtle speech patterns, with potential applications in mental health screening and assistive diagnostic systems.

          This project strengthened my expertise in multimodal deep learning, transformer architectures, and efficient model optimization for healthcare AI.


  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      Here are some of the core skills and technologies I have worked with:

      - **Programming Languages:** Python, C++
      - **LLMs and Generative AI:** LangChain, LangGraph, LangSmith, Hugging Face, Agentic-RAG, RAGAS-LLM Evaluator, Vision Transformers, GANs, Diffusion Models
      - **Deep Learning Frameworks:** PyTorch, TensorFlow, Keras, TensorFlow Federated
      - **Web Development Technologies:** FastAPI, Gradio, Flask, Streamlit, RESTful APIs
      - **Libraries:** Scikit-learn, Pandas, NumPy, Matplotlib
      - **SOTA Architectures:** YOLOv5/YOLOv8, EfficientNet, ResNet, ViT, UNet
      - **Cloud and DevOps Tools:** Azure ML, Databricks, Google Colab, Kaggle, Docker, Git, LaTeX


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
