# Site
repository: Alokkiitdh.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alok
title: AI Engineer
email: aloklashok@gmail.com
# website: www.github.com/Alokiitdh/Alokkiitdh.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Alokiitdh
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: __spartan___x
linkedin_username: alok-b58317148
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Hugging Face
  icon: fa fa-connectdevelop
  url: https://huggingface.co/AlokVishwakarma

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name’s Alok and I’m an AI Engineer. I have completed my M.Tech. in Communication Signal Processing and Machine Learning from IIT Dharwad, where I focused on machine learning and deep learning.

  I have experience building intelligent multi-agent systems using LangGraph, LangChain, and LLMs. I’ve developed production-ready APIs with FastAPI, integrated external tools like web search, and worked with vector databases like FAISS and Pinecone for efficient semantic retrieval. I’ve also worked on advanced RAG pipelines, implemented real-time object tracking and counting systems, and built generative and classification models using CNNs, Vision Transformers, and diffusion techniques.

  Along the way, I’ve gained strong problem-solving, debugging, and collaboration skills, and I’m passionate about building real-world AI applications.


content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tipstat 
        link: tipstat.com
        # link_text: boringcompany.com
        sub_title: AI Engineer Intern
        caption: May 2025 - Present
        quote: >
          Building intelligent systems with LangGraph, FastAPI, and LLMs to solve real-world AI challenges.
        description: | # this will include new lines to allow paragraphs
            I have designed and evaluated Retrieval-Augmented Generation (RAG) pipelines using LangGraph, LangChain, and LLMs, with performance benchmarking through RAGAS. My work includes building agentic workflows using LangGraph and leveraging LangSmith for tracing, debugging, and automating complex, multi-step behaviors.

            I’ve developed production-ready APIs using FastAPI, integrated external tools like web search into multi-agent systems, and utilized CLI tools to streamline and automate development workflows. I enjoy working at the intersection of infrastructure, intelligence, and innovation to bring powerful AI products to life.


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Indian Institute of Technology Dharwad
        caption: 2023 - 2025
        sub_title: M.Tech – Communication Signal Processing and Machine Learning (CSPML)
        cpi: 8.07/10
        quote: >
          Where my passion for AI and machine learning turned into hands-on expertise.
        description: | # this will include new lines to allow paragraphs
          During my time at IIT Dharwad, I developed a strong foundation in machine learning, deep learning, and signal processing. The program provided both theoretical depth and practical exposure, allowing me to work on real-world projects involving generative AI, vision transformers, and diffusion models.

          I also gained experience in research-driven development, time-bound problem solving, and collaborative teamwork—all of which shaped my journey as an AI engineer.
      - layout: left
        title: Government College of Engineering and Technology, Bikaner
        caption: 2016 - 2020
        sub_title: B.Tech – Electronics and Communication Engineering
        cpi: 9.0/10
        quote: >
          The place where I built my technical foundation and curiosity for AI.
        description: | # this will include new lines to allow paragraphs
            I completed my undergraduate studies in Electronics and Communication Engineering, where I developed strong fundamentals in mathematics, signal processing, and embedded systems. This is where I was first introduced to programming, machine learning, and computer vision, which later evolved into my core areas of interest. I actively participated in technical events and projects, laying the groundwork for my future in AI.

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      Here are some of the core skills and technologies I have worked with:

      - **Programming Languages:** Python, C++
      - **LLMs and Generative AI:** LangChain, LangGraph, LangSmith, Hugging Face, Agentic-RAG, RAGAS-LLM Evaluator, Vision Transformers, GANs, Diffusion Models
      - **Deep Learning Frameworks:** PyTorch, TensorFlow, Keras, TensorFlow Federated
      - **Web Development Technologies:** FastAPI, Gradio, Flask, Streamlit, RESTful APIs
      - **Libraries:** Scikit-learn, Pandas, NumPy, Matplotlib
      - **SOTA Architectures:** YOLOv5/YOLOv8, EfficientNet, ResNet, ViT, UNet
      - **Cloud and DevOps Tools:** Azure ML, Databricks, Google Colab, Kaggle, Docker, Git, LaTeX


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
