# Site 
repository: Alokiitdh/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alok Vishwakarma
title: AI/ML Researcher | Generative AI | LangGraph | LLM Agents
email: aloklashok@gmail.com
website: https://github.com/Alokiitdh

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: Alokiitdh
linkedin_username: alok-b58317148
huggingface_username: AlokVishwakarma

# Additional icon links
additional_links:
  - title: Hugging Face
    icon: fas fa-brain
    url: https://huggingface.co/AlokVishwakarma

# About Section
about_profile_image: images/profile.jpg
about_content: |
  AI/ML Researcher with expertise in Generative AI, LLM Agents, Retrieval-Augmented Generation (RAG), and Computer Vision. I enjoy building scalable, intelligent AI systems with modern tools like LangGraph, Hugging Face, PyTorch, Azure, and FastAPI. I'm currently pursuing my M.Tech in CSPML from IIT Dharwad.

  I'm most skilled in: <mark>LangGraph</mark>, <mark>Generative AI</mark>, <mark>LLMs</mark>, and <mark>FastAPI</mark>.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: AskMyPDF – RAG-based AI Chatbot
        link: https://github.com/Alokiitdh
        additional_links:
          - title: Project Repository
            icon: fab fa-github
            url: https://github.com/Alokiitdh
        quote: >
          Enables interactive conversations with uploaded PDFs using LLMs and FAISS.
        description: |
          Built a FastAPI backend supporting document upload and chat interface using LangGraph. Integrated Groq’s LLaMA 3.3-70B for smart, contextual responses and ensured privacy via auto-cleanup. Evaluated using RAGAS.

      - layout: top-middle
        title: CrowdFlow – People Counting System
        quote: >
          Real-time people detection and counting using YOLOv8 and SORT.
        description: |
          Implemented custom directional counters and visual overlays for public space analytics.

      - layout: top-middle
        title: PDF Summarizer Agent
        description: |
          Summarizes PDFs and answers questions using OpenAI + Pinecone. Built as a smart assistant with conversational capabilities.

      - layout: top-middle
        title: Diffusion Model: Realistic Face Generation
        description: |
          Built DDPM-based generator for anime faces using U-Net and custom dataset. Trained from scratch with PyTorch.

      - layout: top-middle
        title: DualWaveNet: Multimodal Depression Detection
        description: |
          Combined speech features (tempograms/log-mel) using ViT to classify depression. Early fusion improved accuracy.

      - layout: top-middle
        title: FakeSpeechNet: Fake Audio Detection
        description: |
          CNN-based detector trained on ASVspoof data using DCT-transformed log-mel spectrograms.

  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: Tipstat
        sub_title: Machine Learning / Generative AI Intern
        caption: May 2025 – Present
        description: |
          - Designed and evaluated RAG pipelines using LangGraph, LangChain, and RAGAS.
          - Built agentic workflows and production APIs with FastAPI.
          - Integrated external tools like web search in multi-agent systems.

      - layout: left
        title: Indian Institute of Technology Dharwad
        sub_title: Teaching Assistant
        caption: Aug 2023 – Apr 2025
        description: |
          - Guided students in NN & DL lab with hands-on assignments.
          - Supported labs on microcontrollers and control systems.
          - Evaluated and mentored students in real-time coursework.

  - title: M.Tech Thesis
    layout: list
    content:
      - layout: left
        title: FORGET: Instance-Wise Data Unlearning
        sub_title: M.Tech Thesis (IIT Dharwad)
        caption: Sep 2024 – Apr 2025
        description: |
          - Developed efficient framework for data unlearning from pretrained models without retraining.
          - Combined adversarial and regularization methods using ResNet-18/50 in PyTorch.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Indian Institute of Technology Dharwad
        sub_title: M.Tech in CSPML
        caption: Aug 2023 – Apr 2025
        quote: >
          Focused on deep learning, signal processing, and machine learning foundations.
        description: |
          GPA: 8.07  
          Courses: Neural Networks, Pattern Recognition, Deep Learning, Speech Processing.

      - layout: left
        title: Govt. College of Engineering & Technology, Bikaner
        sub_title: B.Tech in ECE
        caption: Aug 2016 – Dec 2020
        description: |
          GPA: 9.0  
          Learned foundational electronics, signal processing, and systems engineering.

  - title: Technical Skills
    layout: text
    content: |
      - **Languages:** Python, C++
      - **Generative AI & LLMs:** LangGraph, LangChain, Hugging Face, RAG, RAGAS, Vision Transformers
      - **Frameworks:** PyTorch, TensorFlow, Keras, TensorFlow Federated
      - **Web Dev:** FastAPI, Gradio, Streamlit, Flask
      - **Libraries:** NumPy, Pandas, Matplotlib, scikit-learn
      - **Cloud/DevOps:** Azure ML, Databricks, Docker, Git
      - **SOTA Architectures:** YOLOv8, ResNet, ViT, U-Net

  - title: A Little More About Me
    layout: text
    content: |
      In my free time, I enjoy:
      - Exploring AI tools
      - Watching tech breakdowns
      - Hiking and fitness
      - Writing clean, open-source code
      - [My GitHub Projects](https://github.com/Alokiitdh)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
